<?php

namespace AppBundle\Repository;

/**
 * EcueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcueRepository extends \Doctrine\ORM\EntityRepository
{
}
