<?php

namespace AppBundle\Repository;

/**
 * HebergeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HebergeRepository extends \Doctrine\ORM\EntityRepository
{
}
