<?php

namespace AppBundle\Repository;

/**
 * MentionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentionRepository extends \Doctrine\ORM\EntityRepository
{
  public function findMention($ecole){
    $q = $this->createQueryBuilder('m')
              ->join('m.filiere','f')
              ->join('f.ecole','e')
              ->where('e.id = :ecole')
              ->setParameter('ecole',$ecole)

    ;
    return $q;

  }
}
