<?php

namespace AppBundle\Repository;

/**
 * MentionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentionRepository extends \Doctrine\ORM\EntityRepository
{
  public function findMention($ecole){
    $q = $this->createQueryBuilder('m')
              ->join('m.filiere','f')
              ->join('f.ecole','e')
              ->where('e.id = :ecole')
              ->setParameter('ecole',$ecole)

    ;
    return $q;

  }
   /**
   * Liste des mentions de la filière
   */
  public function findMentionByFiliere($filiere)
  {
    return $q = $this->createQueryBuilder('m')
                      ->innerJoin('m.filiere', 'f')
                      ->andWhere('f.id = :filiere')
                      ->orderBy('m.libmention', 'ASC')
                      ->setParameter('filiere', $filiere)
                      ->getQuery()->getResult()
    ;
  }
}
