<?php

namespace AppBundle\Repository;

/**
 * ParcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcoursRepository extends \Doctrine\ORM\EntityRepository
{
    /**
   * Liste des Parcours de la Mention
   */
  public function findParcoursByMention($mention)
  {
    return $q = $this->createQueryBuilder('p')
                      ->innerJoin('p.mention', 'm')
                      ->andWhere('m.id = :mention')
                      ->orderBy('p.libparcours', 'ASC')
                      ->setParameter('mention', $mention)
                      ->getQuery()->getResult()
    ;
  }

    /**
   * Recupération
   */
  public function findMaquettesByIdParcours($parcoursid)
  {
    return $q = $this->createQueryBuilder('p')
                      ->addSelect('m')
                      ->addSelect('f')
                      ->innerJoin('p.mention', 'm')
                      ->innerJoin('m.filiere', 'f')
                      ->andWhere('p.id = :parcours')
                      ->orderBy('p.libparcours', 'ASC')
                      ->setParameter('mention', $mention)
                      ->getQuery()->getResult()
    ;
  }
}
