<?php

namespace AppBundle\Repository;

/**
 * TformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TformationRepository extends \Doctrine\ORM\EntityRepository
{
}
