<?php

namespace AppBundle\Repository;

/**
 * TypeueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeueRepository extends \Doctrine\ORM\EntityRepository
{
}
